# This is a basic workflow to help you get started with Actions
name: DAST

on:
  push:
    branches: 
      - master

jobs:

  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://testphp.vulnweb.com'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
    
 
         
